name       : zellij
version    : 0.39.0
release    : 2
source     :
    - https://github.com/zellij-org/zellij/archive/refs/tags/v0.39.0.tar.gz : dee3c677eb4545d302895e1c0020f7da9aba8b154927c6ff215b59aec4fbec9f
homepage   : https://zellij.dev
license    : MIT
component  : system.utils
summary    : A terminal workspace with batteries included
description: |
    Zellij is a terminal workspace. It has the base functionality of a terminal multiplexer (similar to tmux or screen) but includes many built-in features that would allow users to extend it and create their own personalized environment.
networking : yes
builddeps  :
    - cargo
    - mandown
setup      : |
    cargo fetch --locked --target "x86_64-unknown-linux-gnu"
build      : |
    cargo build --release --frozen

    # Build completions
    ./target/release/zellij setup --generate-completion bash > target/zellij.bash
    ./target/release/zellij setup --generate-completion fish > target/zellij.fish
    ./target/release/zellij setup --generate-completion zsh > target/zellij.zsh

    # Build manpage
    mandown docs/MANPAGE.md > assets/zellij.1
install    : |
    install -Dm755 target/release/zellij -t "$installdir/usr/bin"

    # Install completions
    install -Dm644 target/zellij.bash "$installdir/usr/share/bash-completion/completions/zellij"
    install -Dm644 target/zellij.fish "$installdir/usr/share/fish/vendor_completions.d/zellij.fish"
    install -Dm644 target/zellij.zsh "$installdir/usr/share/zsh/site-functions/_zellij"

    # Install manpage
    install -Dm644 assets/zellij.1 "$installdir/usr/share/man/man1/zellij.1"

    # Install desktop file
    install -Dm644 assets/zellij.desktop "$installdir/usr/share/applications/zellij.desktop"
