name       : syncthing
version    : 1.24.0
release    : 84
homepage   : https://syncthing.net
source     :
    - https://github.com/syncthing/syncthing/releases/download/v1.24.0/syncthing-source-v1.24.0.tar.gz : 4a9459667f9b70a7d1e7d572c7c9d02431ef8f055679eef368300ce1a826608f
license    : MPL-2.0
component  : network.util
networking : yes
summary    : Syncthing is an open-source file synchronization client/server application
description: |
    Syncthing is an open-source file synchronization client/server application, written in Go, implementing its own, equally free Block Exchange Protocol. All transit communications between syncthing nodes are encrypted, and all nodes are uniquely identified with cryptographic certificates.
builddeps  :
    - git
    # - golang # re-add for build after 1.23.7
# remove for build after 1.23.7
setup      : |
    curl -sSL https://go.dev/dl/go1.20.7.linux-amd64.tar.gz | tar xz
# remove for build after 1.23.7
environment: |
    export PATH="$PATH:$PWD/go/bin"
build      : |
    go run build.go -no-upgrade -version v${version} build
install    : |
    # Install binaries and other stuff
    install -Dm00755 syncthing $installdir/usr/bin/syncthing
    install -Dm00644 etc/linux-systemd/system/syncthing@.service $installdir/%libdir%/systemd/system/syncthing@.service
    install -Dm00644 etc/linux-systemd/user/syncthing.service $installdir/%libdir%/systemd/user/syncthing.service
    install -Dm00644 etc/linux-desktop/syncthing-ui.desktop $installdir/usr/share/applications/syncthing-ui.desktop
    install -Dm00644 etc/linux-desktop/syncthing-start.desktop $installdir/usr/share/applications/syncthing-start.desktop
    install -Dm00644 assets/logo-only.svg $installdir/usr/share/icons/hicolor/scalable/apps/syncthing.svg
    for sz in 32 64 128 256 512; do
        install -Dm00644 assets/logo-${sz}.png $installdir/usr/share/icons/hicolor/${sz}x${sz}/apps/syncthing.png
    done
    install -Dm00644 etc/firewall-ufw/syncthing $installdir/etc/ufw/applications.d/syncthing
    # Install man pages
    cd man
    install -Dm00644 syncthing.1 $installdir/usr/share/man/man1/syncthing.1
    for file in $(find . -name '*.5' -print); do
        install -Dm00644 $file $installdir/usr/share/man/man5/$file
    done
    for file in $(find . -name '*.7' -print); do
        install -Dm00644 $file $installdir/usr/share/man/man7/$file
    done
