name       : xfce4-desktop-branding
version    : '1.0.0'
release    : 2
source     :
    - git|https://github.com/getsolus/xfce4-desktop-branding.git : 36aecab3aacfc95b4674974f9b1596743ba36a0c
homepage   : https://github.com/getsolus/xfce4-desktop-branding
license    : GPL-2.0-only
component  :
    - desktop.xfce
summary    :
    - Defaults for the XFCE4 Desktop.
description:
    - Defaults for the XFCE4 Desktop.
rundeps    :
    - breeze-cursor-theme
    - font-hack-ttf
    - noto-sans-ttf
    - noto-serif-ttf
    - papirus-icon-theme
    - qogir-gtk-theme
    - qtstyleplugins
    - solus-artwork
install    : |
    %make_install
    install -Dm00644 $pkgfiles/solus-xfce.desktop $installdir/usr/share/xsessions/solus-xfce.desktop
    install -Dm00644 $pkgfiles/56solus-session $installdir/usr/share/defaults/etc/profile.d/56-solus-session.sh
    install -Dm00644 $pkgfiles/60-solusxfce.conf $installdir/usr/share/lightdm/lightdm.conf.d/60-solusxfce.conf