name       : btrfs-progs
version    : 6.6.1
release    : 56
source     :
    - https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.6.1.tar.xz : 3e92cb6d83bdde612318fd8046dd6eff47c786e59d56dd4ece987945d5137c9e
license    : GPL-2.0-only
homepage   : https://btrfs.wiki.kernel.org/index.php/Main_Page
summary    :
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
component  :
    - system.utils
    - libbtrfs : system.base
description:
    - Utilities for managing btrfs filesystems
    - libbtrfs : Library for managing btrfs filesystems
patterns   :
    - libbtrfs :
        - /usr/lib64/libbtrfs.so.*
        - /usr/lib64/libbtrfsutil.so.*
builddeps  :
    - pkgconfig(ext2fs)
    - pkgconfig(libzstd)
    - pkgconfig(lzo2)
    - pkgconfig(python3)
    - pkgconfig(reiserfscore)
    - asciidoc
    - python-sphinx
    - xmlto
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
