name       : typst
version    : 0.8.0
release    : 1
source     :
    - https://github.com/typst/typst/archive/refs/tags/v0.8.0.tar.gz : 4b7886e312171b66fb33b7ad49c4df76748231d0047fb96b407c926070a5d9f9
homepage   : https://typst.app
license    : Apache-2.0
component  : office
summary    : A new markup-based typesetting system that is powerful and easy to learn
description: |
    Typst is a new markup-based typesetting system that is designed to be as powerful as LaTeX while being much easier to learn and use.
networking : yes
builddeps  :
    - cargo
setup      : |
    cargo fetch --locked
build      : |
    cargo build --frozen %JOBS% --release -p typst-cli
install    : |
    install -Dm00755 target/release/typst -t $installdir/usr/bin
